### ISSUE TITLE
SecurityToken

### ISSUE THREAD

**Issue by graysonchen** [rockuw/sts-app-server#1]
https://github.com/rockuw/sts-app-server/blob/master/server.rb#L45
Security需要改成SecurityToken

```
Can't get a federation token
```

**Comment by rockuw** [comment]
这取决于客户端的使用，不过这里叫SecurityToken是好一点。

**Comment by graysonchen** [comment]
我从官网下载的anrdoid demo！返回的json应该是SecurityToken而不是Security!
`http://oss-demo.aliyuncs.com/app-server/sts.php?spm=5176.docoss/practice/app_server/sts_server.2.3.By4CFo`

```
{"status":200,"AccessKeyId":"STS.","AccessKeySecret":"iLmPBVDG1hlCdelqAg5lQLf7MxdA9M3Mqr8OKvRm","SecurityToken":"","Expiration":"2016-02-05 08:53:41 UTC"}
```

**Comment by graysonchen** [comment]
`'Security' => token.security_token,`
replace 
`'SecurityToken' => token.security_token,`

https://github.com/rockuw/sts-app-server/blob/master/server.rb#L45

**Comment by rockuw** [comment]
Fine

**Comment by rockuw** [comment]
84030e5
